jdk:
  - oraclejdk8
language: scala
script: sbt testfull
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
sudo: false
